### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by bjendres** [systopia/de.systopia.signatures#3]
@jensschuppe: Is there a reason we shouldn't...?

**Comment by jensschuppe** [comment]
Not really, although we should point out there is a length restriction due to all signatures per contact being stored in a CiviCRM setting record, which does not allow more than 64KB - and this not being the "real" character length because the signatures are being base64-encoded to avoid encoding problems.

This should be refactored to be stored in custom fields on contacts in a follow-up issue.

**Comment by bjendres** [comment]
@jensschuppe  Could you then please create an issue for this here, so people can see? I would still go ahead and release a ``1.0``.

**Comment by jensschuppe** [comment]
Created #4.

**Comment by jensschuppe** [comment]
Released [Signatures 1.0](https://github.com/systopia/de.systopia.signatures/releases/tag/1.0)
