### ISSUE TITLE
Signatures not saving in CiviCRM 5.21

### ISSUE THREAD

**Issue by xpdientUK** [systopia/de.systopia.signatures#6]
I'm creating the signatures, but they are not saving. When you go away from the contact and then retrn, the signature fields are blank. Cosequently the tokens aren't working either.

**Comment by bjendres** [comment]
Hi @xpdientUK. Could you please post you CiviCRM version, extension version and CMS version?

**Comment by xpdientUK** [comment]
Drupal 7.69, CiviCRM 5.21.0, Signatures 1.2-dev

**Comment by bjendres** [comment]
Thanks a lot, @xpdientUK, I have identified and fixed the issue.

One remark though: I would recommend installing a properly released version of this (or any) extension, instead of installing the latest commit from the ``master`` branch. You can always find the latest release here: https://github.com/systopia/de.systopia.signatures/releases/latest. Our last version ``1.1`` didn't have the issue described here.

**Comment by xpdientUK** [comment]
Great stuff Bjorn - I’ll reload and test

**Comment by xpdientUK** [comment]
Works great.

Thanks


	
Tony Horrocks
Director
Xpdient CIC
p:	07515557002  m: 07515557002
a:	5, Darenth Road
 	London N16 6EP
w:	xpdient.co.uk <https://xpdient.co.uk/>  e: tony@xpdient.co.uk <mailto:tony@xpdient.co.uk>
fb:	XpdientUK <https://www.facebook.com/xpdientUK/>  tw: @xpdientUK <https://twitter.com/xpdientUK>
